# Site settings
title: "Windows IoT"
email:
description: "Get Windows and development tools to easily build and manage the next generation of Internet of Things solutions on multiple platforms."
keywords: "Internet of Things, Internet of Your Things, IoT, Windows IoT, Microsoft IoT, Connected Devices, Windows Universal Apps, Universal Apps, Windows 10, Windows 10 IoT Core, Development Board, Raspberry Pi, Raspberry Pi 2, Intel Galileo, Intel Galileo Gen 2, Galileo, MinnowBoard Max, MBM, Windows Developers, Windows Developer Program for IoT, Makers, Maker Faire, Internet Connected Devices, Connect the Dots, .NET Micro Framework, .NET MF, Windows Embedded, Arduino, Smart things, Smart devices, Smart connected devices, Home Automation, Robot, Maker Cloud, Windows Analytics, Windows Dashboard"
baseurl: "/content"
url: "http://ms-iot.github.io/content"
repositoryurl: "https://github.com/ms-iot/content/blob/develop/"
landingurl: "http://dev.windows.com/iot"
hacksterurl: "http://microsoft.hackster.io"
hardwareurl: "http://go.microsoft.com/fwlink/p/?linkID=532948"
signupurl: "https://www.windowsondevices.com/signup.aspx"
downloadurl: "http://connect.microsoft.com/windowsembeddedIoT/Downloads/"


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: pretty
highlighter: pygments
safe: true
lsi: false

desc:
    en-US: "english"
